USE [master]
GO
CREATE LOGIN [etl] WITH PASSWORD=N 'test_pwd', DEFAULT_DATABASE=[AdventureWorksDW2019], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE USER [etl] FOR LOGIN [etl]
GO
USE [AdventureWorksDW2019]
GO
ALTER ROLE [db_datareader] ADD MEMBER [etl]
GO
USE [master]
GO
GRANT CONNECTION SQL TO [etl]
GO